/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import project_java.ViewCarte;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import project_java.javaconnect;
import java.sql.*;
/**
 *
 * @author amiratechnologier
 */
public class MEDQNT extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public MEDQNT() {
        setUndecorated(true);
        setLocationRelativeTo(null);
        initComponents();
        conn=javaconnect.ConnecrDb();
    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldQNTS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQNTP = new javax.swing.JTextField();
        jButtonMDFY = new javax.swing.JButton();
        jButtonMDFY1 = new javax.swing.JButton();
        IDMED = new javax.swing.JLabel();
        idC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Quantity in Stock           :");

        jTextFieldQNTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQNTSActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Quantity to Purchase      :");

        jTextFieldQNTP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldQNTP.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldQNTP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jTextFieldQNTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQNTPActionPerformed(evt);
            }
        });

        jButtonMDFY.setBackground(new java.awt.Color(248, 16, 38));
        jButtonMDFY.setText("Cancel");
        jButtonMDFY.setBorder(null);
        jButtonMDFY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMDFY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMDFYActionPerformed(evt);
            }
        });

        jButtonMDFY1.setBackground(new java.awt.Color(28, 248, 28));
        jButtonMDFY1.setText("Purchase");
        jButtonMDFY1.setBorder(null);
        jButtonMDFY1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMDFY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMDFY1ActionPerformed(evt);
            }
        });

        IDMED.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N

        idC.setBackground(new java.awt.Color(255, 255, 255));
        idC.setForeground(new java.awt.Color(255, 255, 255));
        idC.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMDFY1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldQNTS, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(jTextFieldQNTP))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jButtonMDFY, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IDMED, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDMED, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQNTS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQNTP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMDFY, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMDFY1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getjTextFieldQNTP() {
        return jTextFieldQNTP;
    }

    public JTextField getjTextFieldQNTS() {
        return jTextFieldQNTS;
    }

    public JLabel getIDMED() {
        return IDMED;
    }

    public JLabel getIdC() {
        return idC;
    }

    
    
    private void jTextFieldQNTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQNTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQNTSActionPerformed

    private void jTextFieldQNTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQNTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQNTPActionPerformed

    private void jButtonMDFYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMDFYActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonMDFYActionPerformed

    private void jButtonMDFY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMDFY1ActionPerformed
        
        int qntS=Integer.parseInt(jTextFieldQNTS.getText());
        int qntP=Integer.parseInt(jTextFieldQNTP.getText());
        
        if (qntP >qntS){
            JOptionPane.showMessageDialog(null,"stock is insufficient");
        } 
        else if(qntP==0 ||qntP<0 ){
            JOptionPane.showMessageDialog(null,"Check if Quantity >0");
        }
        else {
            ViewCarte  vct=new ViewCarte();
            
            /*DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm");
	    Date date;
            date = new Date();
            String sql ="Insert into customer_meds(med_id,med_name,med_number,med_man,med_exp,med_qt,med_price) select * from meds where med_id="+Integer.parseInt(IDMED.getText())+"";
            String sql2 ="update customer_meds "
            + "set customer_id="+1+",med_qt="+qntP+",date_ajout="+dateFormat.format(date)+""
            + " where med_id="+Integer.parseInt(IDMED.getText())+"and date_ajout="+dateFormat.format(date)+""; 
            String sql3="update meds "
            + "set med_qt='"+(qntS-qntP)+"'where med_id="+Integer.parseInt(IDMED.getText())+""; */
            
          
           
        try{
            // i will solve it inchallah
            /*
            String sql1 ="update customer_meds "
            + "set med_qt=med_qt+"+qntP+""
            + " where med_id="+Integer.parseInt(IDMED.getText())+" and customer_id="+1+""; 
            String sql2="update meds "
            + "set med_qt="+(qntS-qntP)+" where med_id="+Integer.parseInt(IDMED.getText())+"";
            pst=conn.prepareStatement(sql1);
            pst.execute();
            pst=conn.prepareStatement(sql2);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");
            setVisible(false);
            */
           // ******************************
            String id=idC.getText();
            String sql="Insert into customer_meds(med_qt,customer_id,date_ajout,med_id,med_name,med_number,med_man,med_exp,med_price) "
                  + "select "+qntP+",(select user_id from users where user_name='"+id+"'),SYSDATE(),med_id,med_name,med_number,med_man,med_exp,med_price from meds where med_id="+Integer.parseInt(IDMED.getText())+" ";
                String sql2="update meds "
            + "set med_qt='"+(qntS-qntP)+"'where med_id="+Integer.parseInt(IDMED.getText())+"";
                /*   String sql3="update customer_meds "
            + "set customer_id=(select user_id from users where user_name='"+id+"')"; */
                 pst=conn.prepareStatement(sql);
                 pst.execute();
                /* pst=conn.prepareStatement(sql3);
                 pst.execute(); */
                 pst=conn.prepareStatement(sql2);
                 pst.execute();
                 JOptionPane.showMessageDialog(null, "Saved"+id);
                 setVisible(false);
        }
        catch(Exception e){
           /* try{
                String id=idC.getText();
                JOptionPane.showMessageDialog(null, e);
                String sql="Insert into customer_meds(med_qt,date_ajout,med_id,med_name,med_number,med_man,med_exp,med_price) "
                  + "select "+id+","+qntP+",SYSDATE(),med_id,med_name,med_number,med_man,med_exp,med_price from meds where med_id="+Integer.parseInt(IDMED.getText())+" ";
                String sql2="update meds "
            + "set med_qt='"+(qntS-qntP)+"'where med_id="+Integer.parseInt(IDMED.getText())+"";
                String sql3="update customer_meds "
            + "set customer_id=select(customer_id from customer_meds where user_name="+id+")";
                 pst=conn.prepareStatement(sql);
                 pst.execute();
                 pst=conn.prepareStatement(sql2);
            pst.execute();
                 JOptionPane.showMessageDialog(null, "Saved");
                 setVisible(false);
            }
            catch(Exception e1){
              */
            JOptionPane.showMessageDialog(null, e );
        }
           /* MODMEDC mdc=new MODMEDC();
            DefaultTableModel model=(DefaultTableModel)vct.getTable().getModel();
            model.addRow(new Object[]{mdc.getjTextFieldMEDID().getText(),mdc.getjTextFieldMEDNAME().getText(),
            mdc.getjTextFieldMEDNUMB().getText(),mdc.getjTextFieldDATEMAN().getText(),
            mdc.getjTextFieldDATEEXP().getText(),mdc.getjTextFieldPRC().getText(),jTextFieldQNTP.getText()});
            // khass tan9ass mn quantite 7ite tn9ssat
            JOptionPane.showMessageDialog(null,"Succes"+jTextFieldQNTP.getText()); */
           
        }
    }//GEN-LAST:event_jButtonMDFY1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MEDQNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MEDQNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MEDQNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MEDQNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MEDQNT().setVisible(true);
            }
        });
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDMED;
    private javax.swing.JLabel idC;
    private javax.swing.JButton jButtonMDFY;
    private javax.swing.JButton jButtonMDFY1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldQNTP;
    private javax.swing.JTextField jTextFieldQNTS;
    // End of variables declaration//GEN-END:variables
}
